INSERT INTO StammdatenKategorie (Kategorie) VALUES('Geschlecht');
INSERT INTO StammdatenKategorie (Kategorie) VALUES('Land');
INSERT INTO StammdatenKategorie (Kategorie) VALUES('Anlass');
INSERT INTO StammdatenKategorie (Kategorie) VALUES('GeschenkKategorie');
INSERT INTO StammdatenKategorie (Kategorie) VALUES('Geschenkbestandteil');

INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(1,'Männlich');
INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(1,'Weiblich');
INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(2,'Deutschland');
INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(2,'Österreich');
INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(2,'Schweiz');
INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(3,'Hochzeit');
INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(3,'Geburtstag');
INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(3,'Dankeschön');
INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(3,'Weihnachten');
INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(3,'Ostern');
INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(4,'Gekauft');
INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(4,'Gebastelt');
INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(5,'Präsent');
INSERT INTO StammdatenWert (KategorieID, Wert) VALUES(5,'Karte');